[Rainmeter]
Update=0
BackgroundMode=2
SolidColor=0,0,0,130
DynamicWindowSize=1
AccurateText=1
DynamicVariables=1

MouseScrollUpAction=[!SetVariable Scale "(#Scale#+0.1)"][!WriteKeyValue Variables Scale "(#Scale#+0.1)"][!Refresh] 
MouseScrollDownAction=[!SetVariable Scale "(#Scale#-0.1 < 0.1 ? 0.1 : #Scale#-0.1)"][!WriteKeyValue Variables Scale "(#Scale#-0.1 < 0.1 ? 0.1 : #Scale#-0.1)"][!Refresh]

[Metadata]
Name=Music Player with Rat
Author=outlawishhh
Description=Simple music player with dancing rat animation and upward-bounding shape visualizer
Version=1.0

[Variables]
Scale=1
RatWidth=174
RatHeight=174
;adjust this based on the number of frames in the folder
FrameCount=134 
CurrentFrame=1
SmallArtSize=70
VisualizerColor=255,255,255,100

@includeBands=#@#MeasureBandsS.inc

[MeasureFrameUpdate]
Measure=Calc
Formula=(#CurrentFrame# >= #FrameCount# ? 1 : #CurrentFrame# + 1)
UpdateDivider=3
DynamicVariables=1
OnUpdateAction=[!SetVariable CurrentFrame "[MeasureFrameUpdate]"][!UpdateMeter MeterRatAnimation][!Redraw]

[MeasureIsPlaying]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=State
UpdateDivider=3
IfCondition=#CURRENTSECTION# = 1
IfConditionMode=1
IfTrueAction=[!EnableMeasure MeasureFrameUpdate][!Redraw]
IfFalseAction=[!DisableMeasure MeasureFrameUpdate][!SetVariable CurrentFrame "1"][!UpdateMeter MeterRatAnimation][!Redraw]

[MeasureAlbumArt]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Cover
DefaultPath=#@#Images\Default.png
CoverPath=#@#Images\cover.png
UpdateDivider=5

[MeasureArtist]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Artist
UpdateDivider=5
Substitute="":"Unknown Artist"

[MeasureTitle]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Title
UpdateDivider=5
Substitute="":"Unknown Title"

[MeasurePosition]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Position
Substitute="":"0:00"

[MeasureDuration]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Duration
UpdateDivider=5
Substitute="":"0:00"

[Progress]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=PROGRESS

[MeasurePlayPause]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=State
Substitute="0":"Play","1":"Pause","2":"Play"

[MeterBG]
Meter=Image
ImageName=#@#Images\MUSIC.png
X=(0*#Scale#)
Y=(0*#Scale#)
W=(462*#Scale#)
H=(190*#Scale#)

[MeterBlackOverlay]
Meter=Shape
X=(0*#Scale#)
Y=(0*#Scale#)
Shape=Rectangle 0,0,(462*#Scale#),(190*#Scale#) | Fill Color 0,0,0,200 | StrokeWidth 0

[MeterRatAnimation]
Meter=Image
ImageName=#@#Images\frames\frame#CurrentFrame#.png
X=(8*#Scale#)
Y=(8*#Scale#)
W=(#RatWidth#*#Scale#)
H=(#RatHeight#*#Scale#)
DynamicVariables=1
PreserveAspectRatio=0
Tile=0

[MeterSmallAlbumArt]
Meter=Image
X=((8+#RatWidth#-#SmallArtSize#-5)*#Scale#)
Y=((8+#RatHeight#-#SmallArtSize#-5)*#Scale#)
W=(#SmallArtSize#*#Scale#)
H=(#SmallArtSize#*#Scale#)
MeasureName=MeasureAlbumArt
PreserveAspectRatio=1
DynamicVariables=1

[MeterArtist]
Meter=String
X=(324*#Scale#)
Y=(24*#Scale#)
W=(220*#Scale#)
ClipString=1
StringAlign=Center
FontColor=220,220,220
FontFace=Segoe UI
FontSize=(14*#Scale#)
StringStyle=Bold
StringCase=Upper
MeasureName=MeasureArtist
AntiAlias=1

[MeterTitle]
Meter=String
X=(318*#Scale#)
Y=(52*#Scale#)
W=(220*#Scale#)
ClipString=1
StringAlign=Center
FontFace=Segoe UI
FontColor=180,180,180
StringCase=Upper
FontSize=(14*#Scale#)
MeasureName=MeasureTitle
AntiAlias=1

[MeterPosition]
Meter=String
X=(231*#Scale#)
Y=(86*#Scale#)
W=(16*#Scale#)
MeasureName=MeasurePosition
FontFace=Segoe UI
FontColor=160,160,160
FontSize=(8*#Scale#)
StringAlign=Left
AntiAlias=1

[MeterDuration]
Meter=String
X=(372*#Scale#)
Y=(86*#Scale#)
W=(16*#Scale#)
FontFace=Segoe UI
FontColor=160,160,160
FontSize=(8*#Scale#)
StringAlign=Left
MeasureName=MeasureDuration
AntiAlias=1

[ProgressBar]
Meter=BAR
MeasureName=Progress
X=(265*#Scale#)
Y=(90*#Scale#)
W=(100*#Scale#)
H=(9*#Scale#)
BarColor=140,140,140
SolidColor=40,40,40
BarOrientation=HORIZONTAL
LeftMouseDownAction=[!CommandMeasure Progress "SetPosition $MouseX:%$"][!UpdateMeasure Progress][!Redraw]

[Previous]
Meter=IMAGE
ImageName=#@#Images\Previous.png
X=(240*#Scale#)
Y=(122*#Scale#)
W=(42*#Scale#)
H=(42*#Scale#)
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "Previous"]
AntiAlias=1

[PlayPause]
Meter=IMAGE
ImageName=#@#Images\[MeasurePlayPause].png
X=(290*#Scale#)
Y=(122*#Scale#)
W=(42*#Scale#)
H=(42*#Scale#)
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "PlayPause"]
DynamicVariables=1

[Next]
Meter=IMAGE
ImageName=#@#Images\Next.png
X=(340*#Scale#)
Y=(122*#Scale#)
W=(42*#Scale#)
H=(42*#Scale#)
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "Next"]
AntiAlias=1

[MeterBar0]
Meter=Shape
X=(8*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand2]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar1]
Meter=Shape
X=(25*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand3]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar2]
Meter=Shape
X=(42*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand4]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar3]
Meter=Shape
X=(59*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand3]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar4]
Meter=Shape
X=(76*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand4]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar5]
Meter=Shape
X=(93*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand5]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar6]
Meter=Shape
X=(110*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand6]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar7]
Meter=Shape
X=(127*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand7]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar8]
Meter=Shape 
X=(144*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand8]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1

[MeterBar9]
Meter=Shape
X=(161*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(14*#Scale#),(-50*#Scale#*[MeasureBand9]) | Fill Color #VisualizerColor# | StrokeWidth 0
DynamicVariables=1
